# Use a Node.js base image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application files
COPY . .

# Expose the port Vite's development server runs on
EXPOSE 5173

# Define the command to start the development server
CMD ["npm", "run", "dev", "--", "--host"]